name: Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pack modpack
        run: |
          cd ./
          mkdir build

          mv ${GITHUB_WORKSPACE} build/overrides
          mv manifest.json build
          mv modlist.html build

          rm -r build/overrides/.github
          rm build/overrides/.gitignore
          rm build/overrides/LICENSE
          rm build/overrides/manifest.json
          rm build/overrides/modlist.html
          rm build/overrides/README.md

      - name: Upload modpack to Actions
        uses: actions/upload-artifact@v3
        with:
          name: YourModpackName
          path: build
